# Using NumPy for Linear Algebra

This is a short interactive tutorial that will give you some basic tools to do Linear Algebra operations. It should also help for Peter's module. Embrace Linear Algebra, it is your friend!

***Note that this is a runnable notebook and as such when you run a cell it stores the variables in memory. This is different to when you run a piece of code and when it ends they are destroyed. Thus you can sometimes run a cell out of order and issues can arise.***

When using NumPy we need to import the library

Click in the cell below and run the cell using Shift+Enter

In [1]:
import numpy as np


We can create vectors in Numpy by using the array data structure.

For example we can create the vectors $\mathbf{a}=\begin{pmatrix}1 \\ 2 \\ 3\end{pmatrix}$ and $\mathbf{b}=\begin{pmatrix}4 \\ 5 \\ 6\end{pmatrix}$.

```python
a = np.array([1,2,3])
b = np.array([4,5,6])
```

We can also do the following multiplications.

## Scalar Multiplication

e.g. $5\mathbf{a} = \begin{pmatrix}5 \\ 10 \\ 15\end{pmatrix}$

```python
5 * a # [5,10,15]
```

## Element-wise Multiplication (Hadamard Product)

This is not a common operation in Maths, but it used a lot more than you might expect.

$a \circ b = \begin{pmatrix}1*4 \\ 2*5 \\ 3*6\end{pmatrix} = \begin{pmatrix}4 \\ 10 \\ 18\end{pmatrix}$


```python
a*b # [1*4, 2*5, 3*6] = [4,10,18]
```

## Dot Product

$a \cdot b = 1\cdot4 + 2\cdot5 + 3\cdot6 = 32$

```python
np.dot(a,b)# 32
```

You can try this below, just hit Shift+Enter again.

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# scalar multiplication
print(f"Scalar multiplication of 5 * {a}")
print(5 * a)

# element-wise multiplication
print(f"\nElement-wise multiplication of {a} and {b}")
print(a * b)

# inner-product (dot product) multiplication i.e. row * vector
print(f"\nDot product multiplication of {a} and {b}")
print(np.dot(a,b))



Scalar multiplication of 5 * [1 2 3]
[ 5 10 15]

Element-wise multiplication of [1 2 3] and [4 5 6]
[ 4 10 18]

Dot product multiplication of [1 2 3] and [4 5 6]
32


## A word on dimensions.

When creating a column vector of size 3 you are really creating an array. This is not strictly a column vector, it has dimensions (3,). It is missing an axis.

```python
# This is not strictly a column vector, it has dimensions (3,). It is missing an axis.
a = np.array([1,2,3])
```

Most operations we do won't care about this, but I want you to see the full picture. Technically a mathematical column vector of size 3 has 3 rows and 1 column, it's dimensions are $3\times 1$ or in python ``(3,1)``.

We can force the issue though!

```python
# This is strictly a column vector, it has dimensions (3,1). It has two axis (three rows and 1 column)
b = np.array([
              [1],
              [2],
              [3]
             ])
```

Try these below. I have printed out the dimensions.

In [4]:
# This is not strictly a column vector, it has dimensions (3,). It is missing an axis.
# You can think of (3,) as (3,1) most of the time
a = np.array([1,2,3])
print(f"The dimension of a is \n{a.shape}\n")

# This is strictly a column vector, it has dimensions (3,1). It has two axis (three rows and 1 column)
b = np.array([
              [1],
              [2],
              [3]
             ])
print(f"The dimension of b is \n{b.shape}\n")

The dimension of a is 
(3,)

The dimension of b is 
(3, 1)



## Matrices and Matrix Multiplication

We can also create matrices using the ``np.array()`` datatype.

To create a matrix with 2 rows and 3 columns

$\mathbf{M_{2\times3}} =
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{pmatrix}$

use the following code.

```python
# This is a matrix with 2 rows and 3 columns (2,3).
M = np.array([[1,2,3],
              [4,5,6]
              ])
```

We can also do matrix multiplication.

e.g.

$
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{pmatrix}
\begin{pmatrix}1 \\ 2 \\ 3\end{pmatrix}
=
\begin{pmatrix}14 \\ 32\end{pmatrix}
$

***Note that the number of columns of the first matrix must match the number of rows of the second matrix (in this case vector which is really just a 1 column matrix!).***

```python
# This is not strictly a column vector, it has dimensions (3,). It is missing an axis.
a = np.array([1,2,3])
# This is a matrix with 2 rows and 3 columns (2,3).
M = np.array([[1,2,3],
              [4,5,6]
              ])

# We can do matrix multiplication because the inner dimensions of M and a (2,3)(3,1) match!
answer = np.dot(M,a) # [14 32]
```

Here we use the ``np.dot()`` function. There are a couple of other ways, but we will stick to this one!

You can try this below. I have also demoed the other ways as well.

In [5]:
# This is not strictly a column vector, it has dimensions (3,). It is missing an axis.
# You can think of (3,) as (3,1) most of the time
a = np.array([1,2,3])
print(f"The dimension of a is \n{a.shape}\n")

# This is strictly a column vector, it has dimensions (3,1). It has two axis (three rows and 1 column)
b = np.array([
              [1],
              [2],
              [3]
             ])
print(f"The dimension of b is \n{b.shape}\n")

# This is a matrix with 2 rows and 3 columns (2,3).
M = np.array([[1,2,3],
              [4,5,6]
              ])

print(f"The dimension of M is \n{M.shape}\n")

# This is matrix multiplication with the .matmul function.
# It will work with either the not strict and strict column vectors a and b.
# We can do matrix multiplication because the inner dimensions of M and a (2,3)(3,1) match!
# The same is true for M and b.
answer1 = np.matmul(M, a)
answer2 = np.matmul(M, b)
print(f"Output of .matmul() for M and a - \n{answer1}\n")
print(f"Output of .matmul() for M and b - \n{answer2}\n")

# This is matrix multiplication with the .dot function.
# It will work with either the not strict and strict column vectors a and b.
answer3 = np.matmul(M, a)
answer4 = np.matmul(M, b)
print(f"M @ a - \n{answer3}\n")
print(f"M @ b - \n{answer4}\n")

# Later versions of Python now have an infix operator which does the same thing.
# It secretly calls the .matmul() function.
answer5 = M @ a
answer6 = M @ b
print(f"Output of .dot() for M and a -\n {answer5}\n")
print(f"Output of .dot() for M and b -\n {answer6}\n")

The dimension of a is 
(3,)

The dimension of b is 
(3, 1)

The dimension of M is 
(2, 3)

Output of .matmul() for M and a - 
[14 32]

Output of .matmul() for M and b - 
[[14]
 [32]]

M @ a - 
[14 32]

M @ b - 
[[14]
 [32]]

Output of .dot() for M and a -
 [14 32]

Output of .dot() for M and b -
 [[14]
 [32]]



## Dimension Error

When the number of columns in the first matrix doesn't equal the number of rows in the second matrix we cannot do matrix multiplication.

e.g. The following matrix multiplication

$
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{pmatrix}
\begin{pmatrix}1 \\ 2 \\ 3\end{pmatrix}
$

is not defined!

The columns of the first matrix (2), doesn't match the rows of the second matrix (3).

The code below shows that this results in a ``ValueError`` and it will let you know the issue!

In [6]:
# This is not strictly a column vector, it has dimensions (3,). It is missing an axis.
a = np.array([1,2,3])

# This is a matrix with 3 rows and 2 columns (3,2).
M = np.array([[1,2],
              [3,4],
              [5,6]
              ])

# Now the dimensions of M and a do not match. You can think of (3,) as (3,1) most of the time.
# If we try and do matrix multiplication we will get an error.
print(M @ a)

# The error thrown here isn't that helpful, but it is saying that the dimensions don't match.
# (3,2)(3,1) Here the inner 2 and 3 do not match!

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [7]:
# This is not strictly a column vector, it has dimensions (3,). It is missing an axis.
a = np.array([1,2,3])

# This is a matrix with 3 rows and 2 columns (3,2).
M = np.array([[1,2],
              [3,4],
              [5,6]
              ])

# If we use np.dot instead we get a more useful error.
print(np.dot(M,a))

# Hence I always tend to use np.dot()

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

## Matrix Inverse

We can compute the inverse of a matrix as follows.

$\mathbf{A} = \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
$

$
\mathbf{A}^{-1} = \frac{1}{ad-bc}\begin{pmatrix}
d & -b \\
-c & a
\end{pmatrix}
$

e.g.

$
\mathbf{A} = \begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
$

$
\mathbf{A}^{-1} = -\frac{1}{2}
\begin{pmatrix}
4 & -2 \\
-3 & 1
\end{pmatrix}
=
\begin{pmatrix}
-2 & 1 \\
\frac{3}{2} & -\frac{1}{2}
\end{pmatrix}
$

We can do this in Python using the ``np.linalg.inv()`` function.

```python
# This is a square matrix with 2 rows and 2 columns (2,2).
M = np.array([[1,2],
              [3,4]
              ])

# We can also find the inverse of a square matrix using np.linalg.inv() (linalg is a linear algebra module)
print(f"The inverse of M is \n{np.linalg.inv(M)}")
```

Try the code below using Shift+Enter

In [8]:
# This is a square matrix with 2 rows and 2 columns (2,2).
M = np.array([[1,2],
              [3,4]
              ])

# We can also find the inverse of a square matrix using np.linalg.inv() (linalg is a linear algebra module)
print(f"The inverse of M is \n{np.linalg.inv(M)}")

The inverse of M is 
[[-2.   1. ]
 [ 1.5 -0.5]]


The following matrix is singular, this means it doesn't have an inverse.

$
\mathbf{A} = \begin{pmatrix}
1 & 2 \\
3 & 6
\end{pmatrix}
$

Again using Python we can see this, in fact we get a ``LinAlgError``.
```python
# This is a square matrix with 2 rows and 2 columns (2,2).
M = np.array([[1,2],
              [3,6]
              ])

# The matrix above is singular, it does not have an inverse.
print(np.linalg.inv(M))

# It will throw a LinAlgError: Singular matrix error!
```

Try the code below using Shift+Enter

In [9]:
# This is a square matrix with 2 rows and 2 columns (2,2).
M = np.array([[1,2],
              [3,6]
              ])

# The matrix above is singular, it does not have an inverse.
print(np.linalg.inv(M))

# It will throw a LinAlgError: Singular matrix error!

LinAlgError: Singular matrix

The reason the following matrix is singular

is because the determinant $ad-bc=0$ and the inverse formular has a $\frac{1}{ad-bc}$ in the formula. You can't divide by zero! The maths is telling you something!

Again Python can do this!

```python
# This is because it's determinant is 0.
# Guess what, there is a function for that too! Yay!
print(f"The determinant of M is {np.linalg.det(M)}")
```

Try the code below using Shift+Enter

In [10]:
# This is because it's determinant is 0.
# Guess what, there is a function for that too! Yay!
print(f"The determinant of M is {np.linalg.det(M)}")

The determinant of M is 0.0


# Solving Systems of Linear Equations

For the following system of linear equations.

$
\begin{align*}
x + 2y &= 1 \\
3x + 4y &= 3
\end{align*}
$

We can represent in matrix form.

$
\begin{equation}
  \begin{pmatrix}
  1 & 2 \\
  3 & 4
  \end{pmatrix}
  \begin{pmatrix}
  x \\
  y
  \end{pmatrix}
  =
  \begin{pmatrix}
  1 \\
  3
  \end{pmatrix}
\end{equation}
$

And solve using the matrix inverse.

$
\begin{equation}
  \begin{pmatrix}
  x \\
  y
  \end{pmatrix}
  =
  \begin{pmatrix}
  1 & 2 \\
  3 & 4
  \end{pmatrix}^{-1}
  \begin{pmatrix}
  1 \\
  3
  \end{pmatrix}
\end{equation}
$

$
\begin{equation}
  \begin{pmatrix}
  x \\
  y
  \end{pmatrix}
  =
  -\frac{1}{2}
  \begin{pmatrix}
  4 & -2 \\
  -3 & 1
  \end{pmatrix}
  \begin{pmatrix}
  1 \\
  3
  \end{pmatrix}
\end{equation}
$

$
\begin{equation}
  \begin{pmatrix}
  x \\
  y
  \end{pmatrix}
  =
  \begin{pmatrix}
  -2 & 1 \\
  \frac{3}{2} & -\frac{1}{2}
  \end{pmatrix}
  \begin{pmatrix}
  1 \\
  3
  \end{pmatrix}
\end{equation}
$

$
\begin{equation}
  \begin{pmatrix}
  x \\
  y
  \end{pmatrix}
  =
  \begin{pmatrix}
  1 \\
  0
  \end{pmatrix}
\end{equation}
$

Spoiler, we can do this in Python!

```python
# This is a square matrix with 2 rows and 2 columns (2,2).
A = np.array([[1,2],
              [3,4]
              ])

b = np.array([1,3])

# We can solve a system of linear equations using the np.linalg.det() function.
x = np.dot(np.linalg.inv(A), b)
```

Try this below.

In [11]:
# Here it is in python!

# This is a square matrix with 2 rows and 2 columns (2,2).
A = np.array([[1,2],
              [3,4]
              ])

b = np.array([1,3])

# We can solve a system of linear equations using the np.linalg.det() function.
x = np.dot(np.linalg.inv(A), b)
print(f"The solution to the system of linear equations is\n {x}\n")

# Note that this answer if you round is actually (1,0)

print(f"Rounded to 2.dp, the solution to the system of linear equations is\n {np.round(x,2)}\n")

The solution to the system of linear equations is
 [1.00000000e+00 2.22044605e-16]

Rounded to 2.dp, the solution to the system of linear equations is
 [1. 0.]

